server:
  port: 8081


spring:
  main:
    environment:
      JAVA_TOOL_OPTIONS: "-Ddruid.mysql.usePingMethod=false"

  mvc:
    servlet:
      load-on-startup: 1
    throw-exception-if-no-handler-found: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.115.228.176/ali
    username: jyjays
    password: Jyjays13475384640@682745$3581
#    url: jdbc:mysql://localhost/dbl1
#    username: root
#    password: jys20030827
  jackson:
      date-format: yyyy-MM-dd HH:mm:ss
      time-zone: GMT+8